import os

REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
ROOM_TTL_SECONDS = 3600
HEARTBEAT_INTERVAL = 5
DEVIATION_THRESHOLD = 1.0
COOLDOWN_MS = 2000
RECONNECT_MAX_RETRIES = 10
HOST_TIMEOUT_SECONDS = 30
